name: Build and Push Docker Image

on:
  push:
    branches:
      - docker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: docker build -t my-react-portfolio .
      
      - name: Tag Docker image
        run: docker tag my-react-portfolio ${{ secrets.DOCKER_USERNAME }}/port
      
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/port
