name: Build and Deploy Docker

# Run on push to the main branch
on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: 21csa56/my-react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Docker Image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: 21csa56/my-react-app:latest
