name: Deploy Dockerized React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker-compose build
      
      - name: Start Docker containers
        run: docker-compose up -d

      - name: Wait for startup
        run: sleep 15s

      - name: Check running containers
        run: docker ps

      - name: Run tests (if applicable)
        # Add your testing commands here

      - name: Clean up
        run: docker-compose down
